# Generated by Django 2.2.1 on 2019-05-19 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('team', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1887), django.core.validators.MaxValueValidator(2019)])),
                ('company', models.CharField(max_length=250)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('collection', models.ManyToManyField(to='card.Collection')),
            ],
        ),
    ]
